
#ifndef NUCLEISEGMENTATION_EXPORT_H
#define NUCLEISEGMENTATION_EXPORT_H

#ifdef NUCLEISEGMENTATION_STATIC_DEFINE
#  define NUCLEISEGMENTATION_EXPORT
#  define NUCLEISEGMENTATION_NO_EXPORT
#else
#  ifndef NUCLEISEGMENTATION_EXPORT
#    ifdef NucleiSegmentation_EXPORTS
        /* We are building this library */
#      define NUCLEISEGMENTATION_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define NUCLEISEGMENTATION_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef NUCLEISEGMENTATION_NO_EXPORT
#    define NUCLEISEGMENTATION_NO_EXPORT 
#  endif
#endif

#ifndef NUCLEISEGMENTATION_DEPRECATED
#  define NUCLEISEGMENTATION_DEPRECATED __declspec(deprecated)
#endif

#ifndef NUCLEISEGMENTATION_DEPRECATED_EXPORT
#  define NUCLEISEGMENTATION_DEPRECATED_EXPORT NUCLEISEGMENTATION_EXPORT NUCLEISEGMENTATION_DEPRECATED
#endif

#ifndef NUCLEISEGMENTATION_DEPRECATED_NO_EXPORT
#  define NUCLEISEGMENTATION_DEPRECATED_NO_EXPORT NUCLEISEGMENTATION_NO_EXPORT NUCLEISEGMENTATION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef NUCLEISEGMENTATION_NO_DEPRECATED
#    define NUCLEISEGMENTATION_NO_DEPRECATED
#  endif
#endif

#endif
